### ISSUE TITLE
Issues with Module Install

### ISSUE THREAD

**Issue by thetootall** [ThomasKur/M365Documentation#10]
I couldnt find any documentation in the repo or any other issues but wanted to raise what I'm seeing on a Windows 10 21H1 with the following $psversiontable info

Name                           Value
----                           -----
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Install-Module M365Documentation -SkipPublisherCheck -AllowClobber -Force
PackageManagement\Install-Package : Access to the cloud file is denied

Import-module M365Documentation
Import-module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)

**Comment by ThomasKur** [comment]
Hello Chris

I assume your Module Directory is on a synced OneDrive. This can lead to the following error "Install-Package : Access to the cloud file is denied". This is not a error related to my module. Try installing it locally via:
`Install-Module M365Documentation -SkipPublisherCheck -AllowClobber -Force -Scope AllUsers`

**Comment by thetootall** [comment]
Ahhh OneDrive Known Folder Redirection strikes again!
This helps with the install-module without error, however trying to import-module M365Documentation I still see:
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
When I try just Connect-M365Doc I receive:
Connect-M365Doc : The 'Connect-M365Doc' command was found in the module 'M365Documentation', but the module could not be loaded. For more information, run 'Import-Module M365Documentation'.
Perhaps more KFR issues?

**Comment by ThomasKur** [comment]
No feedback
