### ISSUE TITLE
AzureAD Component The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by mbroaders** [ThomasKur/M365Documentation#19]
Have this working fine for the Intune Component but when running for the AzureAD component i get the below output . This is using the built in app registration.

Invoke-DocGraph : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\M365Documentation\3.1.2\Internal\Collector\AzureAD\Get-AADPolicy.ps1:140
char:34
+ ... .Objects = (Invoke-DocGraph -Path "/identity/continuousAccessEvaluati ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-DocGraph

**Comment by thetechgy** [comment]
I'm seeing this same error when I run the Intune component

Invoke-DocGraph : The remote server returned an error: (404) Not Found.
At C:\Program
Files\WindowsPowerShell\Modules\M365Documentation\3.1.2\Internal\Collector\Intune\Get-MdmAppleConfiguration.ps1:21
char:23
+ ... c.Objects = Invoke-DocGraph -Path "/deviceManagement/applePushNotific ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-DocGraph

**Comment by ThomasKur** [comment]
This error is generated in some cases for example:
- There is for example no Apple APN Configuration in the Tenant, like thetechgy highlights. The problem I can't really check and suppress the error in these cases.
- In Intune a profile is assigned to a group which was then deleted in Azure AD. The reference to this group still exists in the background. Here I have just commited and update which will hide these errors.
