### ISSUE TITLE
Used application does not have sufficiant permission to access: https://graph.microsoft.com/v1.0/organization

### ISSUE THREAD

**Issue by sokoloffmaks** [ThomasKur/M365Documentation#22]
hi , getting this error
Connect-M365Doc
$doc = Get-M365Doc -Components azuread
Used application does not have sufficiant permission to access: https://graph.microsoft.com/v1.0/organization
At C:\Program Files\WindowsPowerShell\Modules\M365Documentation\3.1.2\Internal\Helper\Invoke-DocGraph.ps1:51 char:13
+             throw "Used application does not have sufficiant permissi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Used applicatio....0/organization:String) [], RuntimeException
    + FullyQualifiedErrorId : Used application does not have sufficiant permission to access: https://graph.microsoft.com/v1.0/organization

all permissions to that application have been provided

**Comment by sokoloffmaks** [comment]
![image](https://user-images.githubusercontent.com/64937759/159195882-7afbac76-dbb6-4277-b5de-97af8c574a27.png)

**Comment by eogmau** [comment]
See this https://github.com/ThomasKur/M365Documentation/issues/2#issuecomment-874760429

**Comment by sokoloffmaks** [comment]
thank you
