### ISSUE TITLE
List of available components

### ISSUE THREAD

**Issue by sokoloffmaks** [ThomasKur/M365Documentation#23]
Hi , trying to generate a report for AIP labels 
Not sure which component to use in command line , I.E 
When using $doc = Get-M365Doc -Components aip, iam  getting errors 
Get-M365Doc : Cannot validate argument on parameter 'Components'.
pls advise 
TIA
PS any change to add aip/dlp/retention  policies into this reporting tool ?

**Comment by ThomasKur** [comment]
Hi, currently the following components are available. AIP and iam are not available:

- AzureAD
- Windows365
- CloudPrint
- InformationProtection
- Intune

Write them as they are written in the above list.
