### ISSUE TITLE
WARNING: Unable to resolve package source 'https://www.poshtestgallery.com/api/v2'.`

### ISSUE THREAD

**Issue by WAing01** [ThomasKur/M365Documentation#24]
When running: Install-Module M365Documentation

this fails with: WARNING: Unable to resolve package source 'https://www.poshtestgallery.com/api/v2'.

`PS C:\temp> Install-Module M365Documentation
WARNING: Unable to resolve package source 'https://www.poshtestgallery.com/api/v2'.`

This could be linked to this issue:  https://github.com/PowerShell/PowerShellGallery/issues/219

Could you deploying to powershellgallery.com as suggested?  thanks for your help.

**Comment by ThomasKur** [comment]
I assume you have not configured the test environment on your client. My module is only pushed and available on the production powershellgallery.com. You can check with:
`Get-PSRepository`

And if the correct one is missing, register it via:
`Register-PSRepository -Default`
