### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by mtaylor1989** [ThomasKur/M365Documentation#25]
Issue 1
After installing the pre-reqs - connect-m365doc from admin powershell pulls prompt for login but gives an access issue to a folder. If I grant everyone access to that folder it works.

Issue 2
after login and running  $doc = Get-M365Doc -Components Intune (or any component) I get constant errors (regardless if its admin powershell or reg user

![image](https://user-images.githubusercontent.com/105072677/167181993-ae191d5e-0bef-4dd8-b1f4-761a536a227f.png)

I have an urgent need that pulling this data would be nice, if I could get an updated app.

Thanks

**Comment by ThomasKur** [comment]
Do you have a special PowerShell Configuration? It looks like it was blocked to load a DLL with an object definition. What PowerShell Version are you using?

**Comment by ThomasKur** [comment]
Please reopen if the issue still persists.
