### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by MUTYRTSSCV567t6** [ThomasKur/M365Documentation#28]
Hi,
I have been running into the following errors

 **New-M365DocAppRegistration Error**

`Set-AzureADApplication : Error occurred while executing SetApplication
Code: Request_BadRequest
Message: Property requiredResourceAccess.resourceAccess is invalid.
RequestId: 58c0b738-f6ae-421a-b8df-df961132b408
DateTimeStamp: Fri, 02 Dec 2022 09:45:11 GMT
Details: PropertyName  - requiredResourceAccess.resourceAccess, PropertyErrorCode  - GenericError
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At C:\Program Files\WindowsPowerShell\Modules\M365Documentation\3.1.2\Internal\Helper\Set-AzureADAppPermission.ps1:35
char:9
+         Set-AzureADApplication -ObjectId $childApp.ObjectId -Required ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureADApplication], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.SetAppl
   ication`
------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------
 **Connect-M365Doc -ClientId $ClientID -ClientSecret (ConvertTo-SecureString $ClientSecret -AsPlainText -Force) -TenantId $TenantID Error**

`Invoke-DocGraph : The remote server returned an error: (404) Not Found.
At C:\Program
Files\WindowsPowerShell\Modules\M365Documentation\3.1.2\Internal\Collector\Intune\Get-MdmAppleConfiguration.ps1:21
char:23
+ ... c.Objects = Invoke-DocGraph -Path "/deviceManagement/applePushNotific ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-DocGraph`
------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------
 **The final set of errors happen when I believe the script is trying to write out the data. The document gets created, and have your logo but no other data**

Get-GroupInfo : Cannot bind argument to parameter 'Groups' because it is an empty array.                                At C:\Program Files\WindowsPowerShell\Modules\M365Documentation\3.1.2\Internal\Collector\Intune\Get-MobileApp.ps1:53    char:50                                                                                                                 +         $DocSec2.Objects = Get-GroupInfo -Groups $AppGroups                                                           +                                                  ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-GroupInfo], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyArrayNotAllowed,Get-GroupInfo

Convert-Path : Cannot find path 'C:\Windows\system32\202212020149-DemoCompany-M365-Doc.docx' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\PSWriteWord\1.1.14\PSWriteWord.psm1:966 char:21
+         $FilePath = Convert-Path -LiteralPath $FilePath
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\syst...y-M365-Doc.docx:String) [Convert-Path], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

Test-Path : Cannot bind argument to parameter 'LiteralPath' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSWriteWord\1.1.14\PSWriteWord.psm1:967 char:36
+         if (Test-Path -LiteralPath $FilePath) {
+                                    ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
   mand

Both Paragraph and WordDocument are null
At C:\Program Files\WindowsPowerShell\Modules\PSWriteWord\1.1.14\PSWriteWord.psm1:1326 char:103
+ ... graph() } else { throw 'Both Paragraph and WordDocument are null' } }
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Both Paragraph and WordDocument are null:String) [], RuntimeException
    + FullyQualifiedErrorId : Both Paragraph and WordDocument are null

**Comment by ThomasKur** [comment]
Could it be that you are using a Proxy which is blocking the connection. Because I se 404 errors and bad requests. These commands are part of the Microsoft PowerShell module and therefore not under my control. Could you recheck?

**Comment by ThomasKur** [comment]
New-M365DocAppRegistration Error --> Fixed

Connect-M365Doc --> Error was generated during Get-M365Doc and can occur if you have no Apple APN configuration within Intune. But you can ignore the warning.

The rest i could not reproduce. Please reopen if you still have the issues.
