### ISSUE TITLE
M365 documentation missing parts on document creation. 

### ISSUE THREAD

**Issue by Cypher1520** [ThomasKur/M365Documentation#29]
Hello, 

First I'd like to say awesome scripts, we used the Intune doc predecessor prior to this and thank you for the work. 

Now the issue, when we run the document exporter against Intune there's a couple things missing. Maybe we're doing it wrong, but wanted to report as capturing some of the items would be beneficial. 

- Settings Catalog Configuration profiles
- Apple Enrollment Program token information

The last item is more of a quality of life item, In the document export the ability to target what header exports go under so we could prefix some content in a template and then export into a certain header so its all sorted.

Again amazing script and thank you for the efforts thusfar!

**Comment by ThomasKur** [comment]
Hello @Cypher1520 I just checked again and Settings Catalog is exported. Also Apple Enrollment Program (Section Name: Apple Configuration) are part of it. But I saw if you specify -ExcludeValues on the Optimize-M365Doc then empty tables are printed in word. Could it be that you did this?

**Comment by ThomasKur** [comment]
ExcludeValues issue is tracked in #33

**Comment by ThomasKur** [comment]
Checkout the new version released to PowerShellGallery https://www.powershellgallery.com/packages/M365Documentation/3.2.0

**Comment by ThomasKur** [comment]
Please reopen if the issue still persists.
