### ISSUE TITLE
Missing TOC

### ISSUE THREAD

**Issue by bike4life** [ThomasKur/M365Documentation#30]
Did our first run. Looking great so far. As other have already said - Thank you for this. 

Our first run did not include a TOC. Ran the example in readME. What did we do wrong?

**Comment by ThomasKur** [comment]
Do you have more information? Have you specified the path to an existing word document, then it is just appending. If the document was not existing then our template is used which contains a TOC, but you need to update it: 
On a Windows platform, press Ctrl+A and then press F9. On a Macintosh platform, press Command+A and then press F9.

Does this solve the problem?

**Comment by ThomasKur** [comment]
Please reopen if the issue still persists.
