### ISSUE TITLE
Update PowerShell Gallery

### ISSUE THREAD

**Issue by ChadSimmons** [ThomasKur/M365Documentation#31]
The module on the [PowerShell Gallery](https://www.powershellgallery.com/packages/M365Documentation) is out of date.  Several updates and bug fixes have been made to the repo, but these are not reflected in the published module.

Thanks!

**Comment by ThomasKur** [comment]
Hello @ChadSimmons, thanks for the feedback. I have just created a new version and uploaded to PowerShellGallery https://www.powershellgallery.com/packages/M365Documentation/3.2.0
