### ISSUE TITLE
Endpoint Security policies

### ISSUE THREAD

**Issue by ArneAbbink** [ThomasKur/M365Documentation#37]
The following Endpoint Security policies are not being documented:

Antivirus:
- Microsoft Defender Antivirus
- Windows Security Experience

Firewall:
- Microsoft Defender Firewall
- Microsoft Defender Firewall Rules

Attack Surface Reduction:
- Attack Surface Reduction Rules

Because of this, creating documentation is still a lot of work. So I hope it's possible to add it. 

Best Regards and keep up the good work!

**Comment by ThomasKur** [comment]
Please test the new version 3.2.2

**Comment by ArneAbbink** [comment]
Unfortunately, the mentioned Endpoint Security policies (under the Endpoint Security node) are still not being documented.
