### ISSUE TITLE
missing Settings catalog profiles

### ISSUE THREAD

**Issue by boivinx7** [ThomasKur/M365Documentation#38]
So in the last 2 week ive been importing all our GPO's to intune and when you migrate it created setting catalog policies, 
and none of those and none of any of the new ones ive made recently show when i re-run the script.

**Comment by boivinx7** [comment]
is it possible that the Query needs a While loop to query more policies ?

**Comment by ThomasKur** [comment]
Please test the new version 3.2.2

**Comment by boivinx7** [comment]
Still loading very little Settings Catalog profiles
