### ISSUE TITLE
Client Secret Conversion Error

### ISSUE THREAD

**Issue by hang10z** [ThomasKur/M365Documentation#4]
Tried to use this command using my app values and tenant id:
Connect-M365Doc -ClientId '00000000-0000-0000-0000-000000000000' -ClientSecret (ConvertTo-SecureString 'SuperSecretString' -AsPlainText -Force) -TenantId '00000000-0000-0000-0000-000000000000'

I get the following error:

Cannot process argument transformation on parameter 'ClientSecret'. Cannot convert the
     | "System.Security.SecureString" value of type "System.String" to type "System.Security.SecureString".

**Comment by ThomasKur** [comment]
Hmm strange on my side this is working. But do I assume correctly, that you had customized the command with your ClientID, TenantId and Secret?

**Comment by Dirk-Manderin** [comment]
I'm getting the same error message as hang10z.  I have verified I'm using the correct ClientId, ClientSecret and TenantId for the application registration I created with New-M365DocAppRegistration.  I'm using PowerShell 5.

**Comment by ThomasKur** [comment]
I have fixed this in the code. Will publish a new version soon.

**Comment by ThomasKur** [comment]
Fixed in actual published version
