### ISSUE TITLE
Powershell Graph SDK

### ISSUE THREAD

**Issue by aotongarcia** [ThomasKur/M365Documentation#41]
Will the module be updated to work with Powershell Graph SDK? With the deprecation of the Azure AD module, how will this module continue to work?

**Comment by ThomasKur** [comment]
I'm not working with the PowerShell Graph SDK. I use "Invoke-RestMethod"...

**Comment by aotongarcia** [comment]
Throughout the module you use soon to be deprecated AzureAD cmdlets. My question was concerning that, apologies if it wasn't clear. Will you be transitioning the AzureAD cmdlets to their equivalent Powershell Graph SDK cmdlets? Otherwise, your module will not work correctly in the future.

**Comment by ThomasKur** [comment]
Please test the new version 3.2.2
