### ISSUE TITLE
List of "Components" Parameter

### ISSUE THREAD

**Issue by DaStivi** [ThomasKur/M365Documentation#46]
Hi, did i just not see ah list of correct/allowed components parameters?

Like "Azure AD"  in Readme Supported Components section is AzureAD for Powershell!?!

Steve

**Comment by jvalente-salemstate** [comment]
Looking at [the function](https://github.com/ThomasKur/M365Documentation/blob/e7affb4c55dbf49b623a8088a694df6e275b2f86/PSModule/M365Documentation/Functions/Get-M365Doc.ps1#L8C1-L13C2) that validates the values,

```powershell
function Get-ValidComponentsValue {
    [CmdletBinding()]
    param()
    $AllCommands = Get-ChildItem -Path "$PSScriptRoot\..\Internal\Collector" -Directory 
    return $AllCommands.Name
}
```
It looks like the values are The directories under [`Internal/Collector`](https://github.com/ThomasKur/M365Documentation/tree/e7affb4c55dbf49b623a8088a694df6e275b2f86/PSModule/M365Documentation/Internal/Collector)

* AzureAD
* CloudPrint
* InformationProtection
* Intune
* Windows365

Having these within the readme would be good, however.

**Comment by snodecoder** [comment]
and the same goes for the supported -IncludeSections / -ExcludeSections, those are located under the corresponding Component directories (strip "Get-" and ".ps1" from the function names to get the Section name)
https://github.com/ThomasKur/M365Documentation/blob/main/PSModule/M365Documentation/Internal/Collector/Intune/Get-MobileAppDetailed.ps1

+1 to explicitly specify the possible Component and Section values in the readme

**Comment by ThomasKur** [comment]
It's now part of the readme and in the next release it will also be available with Get-Help.
