### ISSUE TITLE
Error while $doc = Get-M365Doc -Components Intune -ExcludeSections "MobileAppDetailed"

### ISSUE THREAD

**Issue by morphi83** [ThomasKur/M365Documentation#49]
Hi,
I get the following Message with a Global Admin:

Used application does not have sufficiant permission to access:
https://graph.microsoft.com/v1.0/organization
In C:\Program
Files\WindowsPowerShell\Modules\M365Documentation\3.3.0\Internal\Helper\Invoke-DocGraph.ps1:62 Zeichen:13
+             throw "Used application does not have sufficiant permissi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Used applicatio....0/organization:String) [], RuntimeExc
   eption
    + FullyQualifiedErrorId : Used application does not have sufficiant permission to access: https://gra
   ph.microsoft.com/v1.0/organization

I think they changed something with MS Graph that its not working any more.

Greetings

**Comment by amadeus916** [comment]
The same is happening to me. Have you found any solutions?

**Comment by amadeus916** [comment]
@morphi83 This is fixed for me. I was using delegated permissions and need to connect using token instead of the default authentication.
